cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:usItemId>/', views.cart_add, name='cart_add'),
# re_path(add/(?P<house_id>[0-9]+)/$',view.cart_add)
    # path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    # post views
    path('', views.product_search, name='product_search'),
    path('product/<str:category_slug>/', views.ProductListView.as_view(), name='product_list_search'),
]

walmartDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('products.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    # path('targetCart/', include('targetCart.urls', namespace='targetCart')),
]

products/models.py
from django.db import models


# Create your models here.
from django.urls import reverse


class Category(models.Model):
    category_name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def get_absolute_url(self):
        return reverse('product:product_list_search',
                       args=[self.category_name])

products/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField()

products/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import FormMixin

from cart.forms import CartAddProductForm
from django.contrib.auth.decorators import login_required
from .forms import SearchForm
# Create your views here.
from .models import Category
from .walmart import scrape_walmart_data
from .target import scrape_target_data

from django.views.decorators.cache import cache_page
def product_search(request, category_slug=None):
    form = SearchForm()
    cart_product_form = CartAddProductForm()
    category_walmart = []
    category_target = []
    query = None
    walmart_data = []
    target_data = []
    categories = Category.objects.all()
    if category_slug:
        category = category_slug
        category_walmart = scrape_walmart_data(category)
        category_target = scrape_target_data(category)

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            walmart_data = scrape_walmart_data(query)

            target_data = scrape_target_data(query)
            # # print(target_data)
    # if category_slug:
    #     category = self.kwargs['category_name'])
    #     context['category'] = self.model.objects.filter(category=category)

    return render(request, 'product.html',
                  {'form': form,
                   'cart_product_form': cart_product_form,
                   'query': query,
                   'walmart_data': walmart_data,
                   'target_data': target_data,
                   'categories': categories,
                   'category_target': category_target,
                   'category_walmart': category_walmart,

                   })


class ProductListView(FormMixin, TemplateView):
    # model = Post
    # context_object_name = 'posts'
    template_name = 'product.html'
    form_class = SearchForm
    cart_product_form = CartAddProductForm()
    paginate_by = 4

    def get_context_data(self, **kwargs):

        category_slug = self.kwargs.get('category_slug')
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['cart_product_form'] = self.cart_product_form

        if category_slug:

            category = self.kwargs['category_slug']
            context['category'] = category
            context['category_walmart_data'] = scrape_walmart_data(category)

            context['category_target_data'] = scrape_target_data(category)

        else:

            if 'query' in self.request.GET:
                form = SearchForm(self.request.GET)
                if form.is_valid():
                    query = form.cleaned_data['query']
                    context['query'] = query
                    context['walmart_data'] = scrape_walmart_data(query)
                    context['target_data'] = scrape_target_data(query)

        return context

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/base.css" %}" rel="stylesheet">
  <link rel="icon" type="image/png" href="{% static 'images/icon.png' %}"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<style>
  #ex4 .p1[data-count]:after {
      position: absolute;
      right: 10%;
      top: 4%;
      content: attr(data-count);
      font-size: 40%;
      padding: .2em;
      border-radius: 50%;
      line-height: 1em;
      color: white;
      background: rgba(255, 0, 0, .85);
      text-align: center;
      min-width: 1em;
  / / font-weight: bold;
  }
  li {

    list-style: none;
  }
  a {
      color: black;
      text-decoration: none;
  }

</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">
      <img src="{% static 'images/logo.png' %}" width="50"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active" style="margin-top: 20px;">
        <a class="nav-link" href="{% url "product:product_search" %}">Search Product From Walmart & Target Store  <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
           {% with total_items=cart|length %}
    {% if total_items > 0 %}

      <a class="nav-link" href="{% url "cart:cart_detail" %}">
          <div id="ex4">
              <span class="p1 fa-stack fa-2x has-badge" data-count="{{ total_items  }}">
                <!--<i class="p2 fa fa-circle fa-stack-2x"></i>-->
                <i class="p3 fa fa-shopping-cart fa-stack-1x xfa-inverse" data-count="{{ total_items  }}"></i>
              </span>
         </div>
      </a>
    {% else %}
          <a class="nav-link" href="{% url "cart:cart_detail" %}">
            <span class="p1 fa-stack fa-2x has-badge" data-count="">
                    <!--<i class="p2 fa fa-circle fa-stack-2x"></i>-->
                <i class="p3 fa fa-shopping-cart fa-stack-1x xfa-inverse" data-count=""></i>
           </span>
          </a>
    {% endif %}
  {% endwith %}

      </li>


    </ul>
      {% if request.user.is_authenticated %}
         Hello {{ request.user.username }},
        <a href="{% url "logout" %}">Logout</a>
    {% else %}
      <a href="{% url "login" %}">Log-in</a>
    {% endif %}
  </div>
</nav>


{#  <div id="header" style="background-color: #000000;">#}
{#    <span class="logo"><img src="{% static 'images/logo.png' %}" width="150" height="80"></span>#}
{#    {% if request.user.is_authenticated %}#}
{#    <ul class="menu">#}
{#      <li class = 'text:bold;' {% if section == "Search" %}class="selected"{% endif %}>#}
{#        <a href="{% url "product:product_search" %}"> Search Product From Walmart & Target Store </a>#}
{#      </li>#}
{#      <li class="cart">#}
{#  {% with total_items=cart|length %}#}
{#    {% if total_items > 0 %}#}
{##}
{#      <a href="{% url "cart:cart_detail" %}">#}
{#          <div id="ex4">#}
{#              <span class="p1 fa-stack fa-2x has-badge" data-count="{{ total_items  }}">#}
{#                <!--<i class="p2 fa fa-circle fa-stack-2x"></i>-->#}
{#                <i class="p3 fa fa-shopping-cart fa-stack-1x xfa-inverse" data-count="{{ total_items  }}"></i>#}
{#              </span>#}
{#         </div>#}
{#      </a>#}
{#    {% else %}#}
{#        <span class="p1 fa-stack fa-2x has-badge" data-count="">#}
{#                <!--<i class="p2 fa fa-circle fa-stack-2x"></i>-->#}
{#            <i class="p3 fa fa-shopping-cart fa-stack-1x xfa-inverse" data-count=""></i>#}
{#       </span>#}
{#    {% endif %}#}
{#  {% endwith %}#}
{#</li>#}
{##}
{##}
{#      <li {% if section == "images" %}class="selected"{% endif %}>#}
{#        <a href="{% url "images:list" %}">Images</a>#}
{#      </li>#}
{#      <li {% if section == "people" %}class="selected"{% endif %}>#}
{#        <a href="#">People</a>#}
{#      </li>#}
{#    </ul>#}
{#  {% endif %}#}
{#  <span class="user">#}
{#    {% if request.user.is_authenticated %}#}
{#      Hello {{ request.user.first_name }},#}
{#      <a href="{% url "logout" %}">Logout</a>#}
{#    {% else %}#}
{#      <a href="{% url "login" %}">Log-in</a>#}
{#    {% endif %}#}
{#  </span>#}
{#  </div>#}
{##}
{#  {% if messages %}#}
{#    <ul class="messages">#}
{#      {% for message in messages %}#}
{#        <li class="{{ message.tags }}">#}
{#          {{ message|safe }}#}
{#            <a href="#" class="close">x</a>#}
{#        </li>#}
{#      {% endfor %}#}
{#    </ul>#}
{#  {% endif %}#}

  <div id="content">
    {% block content %}
    {% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script>
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });

    $(document).ready(function(){
      {% block domready %}
      {% endblock %}
    });
  </script>

</body>
</html>

templates/base_test.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/base.css" %}" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<style>
  #ex4 .p1[data-count]:after {
      position: absolute;
      right: 10%;
      top: 4%;
      content: attr(data-count);
      font-size: 40%;
      padding: .2em;
      border-radius: 50%;
      line-height: 1em;
      color: white;
      background: rgba(255, 0, 0, .85);
      text-align: center;
      min-width: 1em;
  / / font-weight: bold;
  }
  li {

    list-style: none;
  }
  a {
      color: black;
      text-decoration: none;
  }

</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="www.metahub.dev">
      <img src="{% static 'images/logo.png' %}" width="50" height="50"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url "product:product_search" %}">Search Products <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
           {% with total_items=cart|length %}
    {% if total_items > 0 %}

      <a class="nav-link" href="{% url "cart:cart_detail" %}">
          <div id="ex4">
              <span class="p1 fa-stack fa-2x has-badge" data-count="{{ total_items  }}">
                <!--<i class="p2 fa fa-circle fa-stack-2x"></i>-->
                <i class="p3 fa fa-shopping-cart fa-stack-1x xfa-inverse" data-count="{{ total_items  }}"></i>
              </span>
         </div>
      </a>
    {% else %}
        <span class="p1 fa-stack fa-2x has-badge" data-count="">
                <!--<i class="p2 fa fa-circle fa-stack-2x"></i>-->
            <i class="p3 fa fa-shopping-cart fa-stack-1x xfa-inverse" data-count=""></i>
       </span>
    {% endif %}
  {% endwith %}

      </li>


    </ul>
      {% if request.user.is_authenticated %}
         Hello {{ request.user.username }},
        <a href="{% url "logout" %}">Logout</a>
    {% else %}
      <a href="{% url "login" %}">Log-in</a>
    {% endif %}
  </div>
</nav>


{#  <div id="header" style="background-color: #000000;">#}
{#    <span class="logo"><img src="{% static 'images/logo.png' %}" width="150" height="80"></span>#}
{#    {% if request.user.is_authenticated %}#}
{#    <ul class="menu">#}
{#      <li class = 'text:bold;' {% if section == "Search" %}class="selected"{% endif %}>#}
{#        <a href="{% url "product:product_search" %}"> Search Product From Walmart & Target Store </a>#}
{#      </li>#}
{#      <li class="cart">#}
{#  {% with total_items=cart|length %}#}
{#    {% if total_items > 0 %}#}
{##}
{#      <a href="{% url "cart:cart_detail" %}">#}
{#          <div id="ex4">#}
{#              <span class="p1 fa-stack fa-2x has-badge" data-count="{{ total_items  }}">#}
{#                <!--<i class="p2 fa fa-circle fa-stack-2x"></i>-->#}
{#                <i class="p3 fa fa-shopping-cart fa-stack-1x xfa-inverse" data-count="{{ total_items  }}"></i>#}
{#              </span>#}
{#         </div>#}
{#      </a>#}
{#    {% else %}#}
{#        <span class="p1 fa-stack fa-2x has-badge" data-count="">#}
{#                <!--<i class="p2 fa fa-circle fa-stack-2x"></i>-->#}
{#            <i class="p3 fa fa-shopping-cart fa-stack-1x xfa-inverse" data-count=""></i>#}
{#       </span>#}
{#    {% endif %}#}
{#  {% endwith %}#}
{#</li>#}
{##}
{##}
{#      <li {% if section == "images" %}class="selected"{% endif %}>#}
{#        <a href="{% url "images:list" %}">Images</a>#}
{#      </li>#}
{#      <li {% if section == "people" %}class="selected"{% endif %}>#}
{#        <a href="#">People</a>#}
{#      </li>#}
{#    </ul>#}
{#  {% endif %}#}
{#  <span class="user">#}
{#    {% if request.user.is_authenticated %}#}
{#      Hello {{ request.user.first_name }},#}
{#      <a href="{% url "logout" %}">Logout</a>#}
{#    {% else %}#}
{#      <a href="{% url "login" %}">Log-in</a>#}
{#    {% endif %}#}
{#  </span>#}
{#  </div>#}
{##}
{#  {% if messages %}#}
{#    <ul class="messages">#}
{#      {% for message in messages %}#}
{#        <li class="{{ message.tags }}">#}
{#          {{ message|safe }}#}
{#            <a href="#" class="close">x</a>#}
{#        </li>#}
{#      {% endfor %}#}
{#    </ul>#}
{#  {% endif %}#}

  <div id="content">
    {% block content %}
    {% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script>
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });

    $(document).ready(function(){
      {% block domready %}
      {% endblock %}
    });
  </script>

</body>
</html>

templates/pagination.html
{#<div class="pagination">#}
{#  <span class="step-links">#}
{#    {% if page.has_previous %}#}
{#      <a href="?page={{ page.previous_page_number }}">Previous</a>#}
{#    {% endif %}#}
{#    <span class="current">#}
{#      Page {{ page.number }} of {{ page.paginator.num_pages }}.#}
{#    </span>#}
{#    {% if page.has_next %}#}
{#      <a href="?page={{ page.next_page_number }}">Next</a>#}
{#    {% endif %}#}
{#  </span>#}
{#</div>#}



<!-- class based pagination -->

<div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                {% else %}
                    <p> no more blogs</p>
                {% endif %}
            </span>
</div>

templates/product.html
{% extends "base.html" %}
{% load products_tags %}


{% block title %}Search{% endblock %}

{% block content %}

<div class = "container">
       <div class="row">
           <div class="col-md-10 col-sm-10">
               {% include 'partials/category.html' %}
           </div>
           <div class="col-md-2 col-sm-6"></div>
       </div>


        <form method="get">

              <div class="form-outline">
                  <input type="search" name="query" id="form1" class="form-control" placeholder="Enter Keyword to Search Product from Walmart or Target "
                  aria-label="Search" />
              </div>
              <input class="text-center btn-lg" type="submit" value="Search" style="margin-top: 10px;">
        </form>


  {% if category %}
    <h1>Products containing "{{ category }}"</h1>

        <div class="row">

          {% for product in category_walmart_data %}
            <div class="col-md-4" style="margin-top: 10px;">

                    <img src="{{ product.image }}" alt="product-image" width="200px" height="200px">
                    <li>{{ product.title|markdown|truncatechars:50 }}</li>
                    <li>{{ product.department }}</li>
                    <li>{{ product.price }}</li>

                    <form action="{% url "cart:cart_add" product.usItemId %}" method="post">
                        {{ cart_product_form }}
                        {% csrf_token %}
                      <input type="submit" value="Add to cart">
                    </form>
            </div>
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
      </div>

    <div class="row">
          <h2> Target Product </h2>
          {% for product in category_walmart_data %}

            <div class="col-md-4" style="margin-top: 50px;">

                    <img src="{{product.image}}{{product.primary_image}}" alt="product-image" width="200px" height="200px">
                    <li>{{ product.title|markdown|truncatechars:50 }}</li>
                    <li>{{ product.merch_class}}</li>
                    <li>{{ product.price }}$</li>
                     <form action="{% url "cart:cart_add" product.usItemId %}" method="post">
                        {{  cart_product_form }}
                        {% csrf_token %}
                      <input type="submit" value="Add to cart">
                    </form>
            </div>
     {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    {% endif %}
  {% if query %}

    <h1>Products containing "{{ query }}"</h1>

        <div class="row">
{#          <h2 style="margin-bottom: 30px;"> Walmart Product </h2>#}
          {% for product in walmart_data %}
            <div class="col-md-4" style="margin-top: 10px;">

                    <img src="{{ product.image }}" alt="product-image" width="200px" height="200px">
                    <li style="list-style: none">{{ product.title|markdown|truncatechars:50 }}</li>
                    <li>{{ product.department }}</li>
                    <li>{{ product.price }}$</li>

                    <form action="{% url "cart:cart_add" product.usItemId %}" method="post">
                        {{ cart_product_form }}
                        {% csrf_token %}
                      <input type="submit" value="Add to cart">
                    </form>
            </div>

    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
        </div>
      </div>

    <div class="row">
          <h2> Target Product </h2>
          {% for product in target_data %}

            <div class="col-md-4" style="margin-top: 50px;">

                    <img src="{{product.image}}{{product.primary_image}}" alt="product-image" width="200px" height="200px">
                    <li>{{ product.title|markdown|truncatechars:50 }}</li>
                    <li>{{ product.merch_class}}</li>
                    <li>{{ product.price }}</li>
                     <form action="{% url "cart:cart_add" product.usItemId %}" method="post">
                        {{  cart_product_form }}
                        {% csrf_token %}
                      <input type="submit" value="Add to cart">
                    </form>
            </div>

    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}

    {% endif %}
        </div>
       </div>
{% endblock %}